=== wurzy/DAW2020-Teste/project-record/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (meta,team,abstract,deliverables)>
<!ELEMENT meta (key,title,subtitle?,bdate,edate,supervisor)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT bdate (#PCDATA)>
<!ELEMENT edate (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>

<!ATTLIST supervisor
    url CDATA #IMPLIED>

<!ELEMENT team (member+)>

<!ELEMENT member (name, email, url?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ATTLIST member 
    id ID #REQUIRED> 

<!ELEMENT abstract (p+)>
<!ELEMENT p (#PCDATA|u|i|b|link)*>
<!ELEMENT i (#PCDATA|b|u|link)*>
<!ELEMENT b (#PCDATA|i|u|link)*>
<!ELEMENT u (#PCDATA|i|b|link)*>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link 
    url CDATA #REQUIRED>

<!ELEMENT deliverables (link+)>

=== wurzy/DAW2020-Teste/project-record/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <meta>
        <key>Teste de DAW 2020-2021</key>
        <title>Teste de DAW 2020-2021</title>
        <subtitle>Resolução dos 2 exercícios do teste de DAW utilizando Node.js</subtitle>
        <bdate>20-Jan-2021</bdate>
        <edate>20-Jan-2021</edate>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <member id="a84464">
            <name>Válter Ferreira Picas Carvalho</name>
            <email>a84464@alunos.uminho.pt</email>
            <url>https://github.com/wurzy</url>
        </member>
    </team>
    <abstract>
        <p>
            Para o exercício 1, foi necessário resolver os seguintes problemas no dataset: acrescentar aspas a todas as chaves; um dos valores de data necessitava de aspas, assim como um dos valores de uma <b>ref</b>; era necessário separar dois objetos por vírgula.
        </p>
        <p>
            Para facilitar a conversão do JSON para o novo formato, foi utilizado o <i>script</i> <b>substituir.js</b>, presente na página do <b>ex1</b>, obtendo assim um novo ficheiro JSON (<b>batismos-fixed.json</b>) com os novos campos indicados no enunciado.
        </p>
        <p>
            Após isso, foi necessário importar para o MongoDB, na base de dados <b>DAW2020</b>, com a collection <b>batismos</b>, através do seguinte comando: "<u>mongoimport --db DAW2020 --collection batismos --file .\batismos-fixed.json --jsonArray</u>"
        </p>
        <p>
            Tudo o resto foi realizado consoante os exemplos das aulas práticas, criação de modelos, controladores e respetivos acessos à base de dados.
        </p>
        <p>
            Este servidor fica à escuta na porta <b>8000</b>, para pedidos de vários utilizadores.
        </p>
        <p>
            Para o exercício 2, é necessário começar pelo aquecimento. Na alínea 1, são <b>21</b> processos nível 3 pertencentes à descendência da classe 900. Na alínea 2, existem <b>1033</b> entidades. Na alínea 3, existem <b>8</b> processos na descendência de <i>900.10</i>. Na alínea 4, existem <b>5</b> processos relacionados com <i>900.10.505</i>. Todas estas alíneas estão presentes na pasta <b>aquecimento</b>.
        </p>
        <p>
            O restante exercício foi realizado com <link url="https://www.w3schools.com/w3css/w3css_downloads.asp">W3.CSS</link>, seguindo os módulos das aulas. Para ser possível verificar a sua funcionalidade, ele fica à escuta na porta <b>8001</b> para os pedidos do utilizador.
        </p>
    </abstract>
    <deliverables>
        <link url="https://github.com/wurzy/DAW2020-Teste">Repositório onde se encontra a resolução do teste</link>
    </deliverables>
</pr>
